name: 'SW - Build System and Package Manager'
description: 'Download and prepare SW tool'
author: 'Egor Pugin'

branding:
  icon: 'box'
  color: 'blue'

runs:
  using: 'node12'
  main: 'dist/main/index.js'
